export enum UserRole {
  CUSTOMER = "CUSTOMER",
  RESTAURANT_OWNER = "RESTAURANT_OWNER",
  KITCHEN_MANAGER = "KITCHEN_MANAGER",
  DELIVERY_PARTNER = "DELIVERY_PARTNER",
  PLATFORM_ADMIN = "PLATFORM_ADMIN",
}